### ISSUE TITLE
Traceback while running the scripts.

### ISSUE THREAD

**Issue by amarts** [aravindavk/gluster-tester#3]
```
[root@localhost ~]# gluster-tester run --testenv=container --num-parallel=5 --backenddir=/d --logdir=/var/logs/gluster-tester 
2019-05-30 10:59:09,659 - INFO - Started bash /usr/lib/python2.7/site-packages/gluster_tester-0.1-py2.7.egg/glustertester/scripts/build-container.sh &>/var/logs/gluster-tester/build-container.log
2019-05-30 11:25:29,406 - INFO - Completed bash /usr/lib/python2.7/site-packages/gluster_tester-0.1-py2.7.egg/glustertester/scripts/build-container.sh &>/var/logs/gluster-tester/build-container.log
Traceback (most recent call last):
  File "/usr/bin/gluster-tester", line 11, in <module>
    load_entry_point('gluster-tester==0.1', 'console_scripts', 'gluster-tester')()
  File "/usr/lib/python2.7/site-packages/gluster_tester-0.1-py2.7.egg/glustertester/main.py", line 112, in main
    subcmd_run(args)
  File "/usr/lib/python2.7/site-packages/gluster_tester-0.1-py2.7.egg/glustertester/main.py", line 79, in subcmd_run
    for num in range(1, args.num_parallel+1):
TypeError: cannot concatenate 'str' and 'int' objects
```

**Comment by amarts** [comment]
```patch
diff --git a/glustertester/main.py b/glustertester/main.py
index 48bae37..be56896 100644
--- a/glustertester/main.py
+++ b/glustertester/main.py
@@ -76,11 +76,11 @@ def subcmd_run(args):
                   env=test_env
     )
 
-    for num in range(1, args.num_parallel+1):
+    for num in range(1, int(args.num_parallel)+1):
         run_else_ignore("docker kill glusterfs-tester-%d" % num)
         run_else_ignore("docker rm glusterfs-tester-%d" % num)
 
-    for num in range(1, args.num_parallel+1):
+    for num in range(1, int(args.num_parallel)+1):
         logdir = os.path.join(args.logdir, "ld-%d" % num)
         bddir = os.path.join(args.backenddir, "bd-%d" % num)
         imgname = "gluster/glusterfs-tester:latest"
@@ -96,7 +96,7 @@ def subcmd_run(args):
         )
 
     run_cmd = "python %s/run-tests.py --num-parallel %d --logdir %s" % (
-        scriptsdir, args.num_parallel, args.logdir
+        scriptsdir, int(args.num_parallel), args.logdir
     )
     if args.ignore_failure:
```

seems to fix the issue.

**Comment by aravindavk** [comment]
`type=int,` for `--num-parallel` is missing in get_args func. Also some directories needs to be created. I will fix this and push again.
